### ISSUE TITLE
Can't get mdx.nvim to work with NVChad

### ISSUE THREAD

**Issue by DeathStroke19891** [davidmh/mdx.nvim#1]
New to nvim, migrating from emacs. Using [NvChad](https://github.com/NvChad/NvChad/) for configuration. Tried some stuff, but can't get .mdx highlighting to work. lazy.nvim doesn't seem to load mdx.nvim when opening a .mdx file. Loading mdx.nvim manually, doesn't seem to enable syntax highlighting either. My config can be found [here](https://github.com/DeathStroke19891/flake_firestorm/blob/38b3bc995d7018c4fec72afa23902754da986c98/home-manager/features/nvim.nix#L241). A standalone [config](https://github.com/DeathStroke19891/flake_firestorm/blob/13cf12f81ef31473653b9866ca8bc72421b0f57c/home-manager/home.nix#L156) without NvChad seems to be working fine when i enable treesitter for the specific buffer manually.

**Comment by davidmh** [comment]
Did a quick search on the NvChad docs and found:

> All NvChad default plugins will have `lazy = true` set. Therefore, if you want a plugin to be enabled on startup, change it to `lazy = false`.
https://nvchad.com/docs/config/plugins

Try adding `lazy = false` to the plugin definition.

**Comment by DeathStroke19891** [comment]
> Did a quick search on the NvChad docs and found:
> 
> > All NvChad default plugins will have `lazy = true` set. Therefore, if you want a plugin to be enabled on startup, change it to `lazy = false`.
> > https://nvchad.com/docs/config/plugins
> 
> Try adding `lazy = false` to the plugin definition.

This fixes the issue, but won't this load mdx.nvim for all buffers even if it is not a .mdx file?

**Comment by davidmh** [comment]
It will load it once on startup, not every time you open a buffer, if you look at the code, it just registers a filetype and configures treesitter to use the markdown parser for mdx filetypes.

https://github.com/davidmh/mdx.nvim/blob/main/lua/mdx/init.lua#L5-L8

The rest of the plugin are just treesitter queries loaded for markdown: `after/queries/markdown`

It won't impact the performance in any way.

**Comment by davidmh** [comment]
Just tested this, if you want to lazy load it, you can use:

`event = 'BufRead *.mdx'`

Using `ft` wouldn't work because `mdx` wouldn't be registered yet.
